#!/bin/bash
# cred-manager.sh v1.1 - Credential management for OpenClaw bots
# Location: /Users/fangjin/cred-manager.sh
# Architecture: local-first, auto-export after writes, NAS sync
set -euo pipefail

CRED_DIR="/Users/fangjin/.credentials"
STORE="$CRED_DIR/store.json"
ENV_FILE="$CRED_DIR/env.secrets"
NAS_BACKUP="/Users/fangjin/nas/.credentials"
JQ=/usr/bin/jq

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

init() {
    mkdir -p "$CRED_DIR" "$NAS_BACKUP"
    chmod 700 "$CRED_DIR"
    if [ ! -f "$STORE" ]; then
        echo '{"credentials":{}}' | $JQ . > "$STORE"
        chmod 600 "$STORE"
    fi
}

auto_export() {
    # Auto-generate env.secrets after any write operation
    local NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    echo "# Auto-generated by cred-manager.sh at $NOW" > "$ENV_FILE"
    $JQ -r '.credentials | to_entries[] | select(.key | startswith("SSH_PASSWORD_") | not) | "\(.key)=\(.value.value)"' "$STORE" >> "$ENV_FILE"
    chmod 600 "$ENV_FILE"
}

auto_sync_nas() {
    # Copy store + env.secrets to NAS (best-effort, don't fail if NAS down)
    cp "$STORE" "$NAS_BACKUP/store-latest.json" 2>/dev/null || true
    cp "$ENV_FILE" "$NAS_BACKUP/env.secrets" 2>/dev/null || true
}

cmd_add() {
    local NAME="$1" VALUE="${2:-}" DESC="${3:-}"
    if [ -z "$VALUE" ]; then echo -n "Value for $NAME: "; read -s VALUE; echo; fi
    if [ -z "$DESC" ]; then echo -n "Description (optional): "; read DESC; fi
    local NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    local TMP=$(mktemp)
    $JQ --arg name "$NAME" --arg val "$VALUE" --arg desc "$DESC" --arg ts "$NOW" \
        '.credentials[$name] = {value: $val, description: $desc, added_at: (.credentials[$name].added_at // $ts), updated_at: $ts}' \
        "$STORE" > "$TMP" && mv "$TMP" "$STORE"
    chmod 600 "$STORE"
    auto_export; auto_sync_nas
    echo -e "${GREEN}Added: $NAME (exported + synced)${NC}"
}

cmd_list() {
    echo -e "${YELLOW}Credentials:${NC}"
    $JQ -r '.credentials | to_entries[] | "  \(.key)\t\(.value.description // "-")"' "$STORE" | column -t -s $'\t'
    local COUNT=$($JQ '.credentials | length' "$STORE")
    echo -e "\n${GREEN}Total: $COUNT credentials${NC}"
}

cmd_get() {
    local NAME="$1"
    local VAL=$($JQ -r --arg name "$NAME" '.credentials[$name].value // empty' "$STORE")
    if [ -z "$VAL" ]; then echo -e "${RED}Not found: $NAME${NC}" >&2; return 1; fi
    echo "$VAL"
}

cmd_delete() {
    local NAME="$1"
    local EXISTS=$($JQ -r --arg name "$NAME" '.credentials[$name] // empty' "$STORE")
    if [ -z "$EXISTS" ]; then echo -e "${RED}Not found: $NAME${NC}" >&2; return 1; fi
    local TMP=$(mktemp)
    $JQ --arg name "$NAME" 'del(.credentials[$name])' "$STORE" > "$TMP" && mv "$TMP" "$STORE"
    chmod 600 "$STORE"
    auto_export; auto_sync_nas
    echo -e "${GREEN}Deleted: $NAME (exported + synced)${NC}"
}

cmd_export() { auto_export; auto_sync_nas; echo -e "${GREEN}Exported to $ENV_FILE${NC}"; }

cmd_backup() {
    local TS=$(date +"%Y%m%d-%H%M%S")
    cp "$STORE" "$NAS_BACKUP/store-$TS.json"
    cp "$STORE" "$NAS_BACKUP/store-latest.json"
    cp "$ENV_FILE" "$NAS_BACKUP/env.secrets" 2>/dev/null || true
    ls -t "$NAS_BACKUP"/store-2*.json 2>/dev/null | tail -n +31 | xargs rm -f 2>/dev/null || true
    echo -e "${GREEN}Backed up to NAS${NC}"
}

cmd_restore() {
    local FILE="${1:-$NAS_BACKUP/store-latest.json}"
    if [ ! -f "$FILE" ]; then echo -e "${RED}Not found: $FILE${NC}" >&2; return 1; fi
    cp "$FILE" "$STORE"; chmod 600 "$STORE"
    auto_export
    echo -e "${GREEN}Restored from $FILE${NC}"
}

cmd_import_env() {
    local FILE="$1" ADDED=0
    if [ ! -f "$FILE" ]; then echo -e "${RED}Not found: $FILE${NC}" >&2; return 1; fi
    while IFS='=' read -r key value; do
        [[ "$key" =~ ^#.*$ ]] && continue; [[ -z "$key" ]] && continue
        value=$(echo "$value" | sed "s/^[\"']//;s/[\"']$//")
        cmd_add "$key" "$value" "imported from $FILE" 2>/dev/null
        ADDED=$((ADDED + 1))
    done < "$FILE"
    echo -e "${GREEN}Imported $ADDED credentials${NC}"
}

usage() { cat << 'EOF'
cred-manager.sh v1.1 - Credential management (local-first + NAS sync)

Usage:
  cred-manager.sh add <NAME> [VALUE] [DESC]
  cred-manager.sh list
  cred-manager.sh get <NAME>
  cred-manager.sh delete <NAME>
  cred-manager.sh export
  cred-manager.sh backup
  cred-manager.sh restore [FILE]
  cred-manager.sh import <FILE>

Writes auto-export env.secrets and sync to NAS after add/delete.
EOF
}

init
case "${1:-help}" in
    add)     cmd_add "${2:-}" "${3:-}" "${4:-}" ;;
    list|ls) cmd_list ;;
    get)     cmd_get "${2:?'name required'}" ;;
    delete|rm) cmd_delete "${2:?'name required'}" ;;
    export)  cmd_export ;;
    backup)  cmd_backup ;;
    restore) cmd_restore "${2:-}" ;;
    import)  cmd_import_env "${2:?'file required'}" ;;
    *)       usage ;;
esac
