#!/bin/bash
# cred-manager.sh v1.0 - Centralized credential management for OpenClaw bots
# Location: /Users/fangjin/cred-manager.sh
set -euo pipefail

CRED_DIR="/Users/fangjin/.credentials"
STORE="$CRED_DIR/store.json"
ENV_FILE="$CRED_DIR/env.secrets"
NAS_BACKUP="/Users/fangjin/nas/.credentials"
JQ=/usr/bin/jq

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

init() {
    mkdir -p "$CRED_DIR" "$NAS_BACKUP"
    chmod 700 "$CRED_DIR"
    if [ ! -f "$STORE" ]; then
        echo '{"credentials":{}}' | $JQ . > "$STORE"
        chmod 600 "$STORE"
        echo -e "${GREEN}Initialized credential store at $STORE${NC}"
    fi
}

cmd_add() {
    local NAME="$1"
    local VALUE="${2:-}"
    local DESC="${3:-}"

    if [ -z "$VALUE" ]; then
        echo -n "Value for $NAME: "
        read -s VALUE
        echo
    fi

    if [ -z "$DESC" ]; then
        echo -n "Description (optional): "
        read DESC
    fi

    local NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    local TMP=$(mktemp)
    $JQ --arg name "$NAME" --arg val "$VALUE" --arg desc "$DESC" --arg ts "$NOW" \
        '.credentials[$name] = {value: $val, description: $desc, added_at: $ts}' \
        "$STORE" > "$TMP" && mv "$TMP" "$STORE"
    chmod 600 "$STORE"
    echo -e "${GREEN}Added: $NAME${NC}"
}

cmd_list() {
    echo -e "${YELLOW}Credentials:${NC}"
    $JQ -r '.credentials | to_entries[] | "  \(.key)\t\(.value.description // "-")\t(\(.value.added_at // "?"))"' "$STORE" | column -t -s $'\t'
    local COUNT=$($JQ '.credentials | length' "$STORE")
    echo -e "\n${GREEN}Total: $COUNT credentials${NC}"
}

cmd_get() {
    local NAME="$1"
    local VAL=$($JQ -r --arg name "$NAME" '.credentials[$name].value // empty' "$STORE")
    if [ -z "$VAL" ]; then
        echo -e "${RED}Not found: $NAME${NC}" >&2
        return 1
    fi
    echo "$VAL"
}

cmd_delete() {
    local NAME="$1"
    local EXISTS=$($JQ -r --arg name "$NAME" '.credentials[$name] // empty' "$STORE")
    if [ -z "$EXISTS" ]; then
        echo -e "${RED}Not found: $NAME${NC}" >&2
        return 1
    fi
    local TMP=$(mktemp)
    $JQ --arg name "$NAME" 'del(.credentials[$name])' "$STORE" > "$TMP" && mv "$TMP" "$STORE"
    chmod 600 "$STORE"
    echo -e "${GREEN}Deleted: $NAME${NC}"
}

cmd_export() {
    local NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
    echo "# Auto-generated by cred-manager.sh at $NOW" > "$ENV_FILE"
    echo "# Do not edit manually - use cred-manager.sh add/delete" >> "$ENV_FILE"
    $JQ -r '.credentials | to_entries[] | "\(.key)=\(.value.value)"' "$STORE" >> "$ENV_FILE"
    chmod 600 "$ENV_FILE"
    local COUNT=$($JQ '.credentials | length' "$STORE")
    echo -e "${GREEN}Exported $COUNT credentials to $ENV_FILE${NC}"
}

cmd_backup() {
    local TS=$(date +"%Y%m%d-%H%M%S")
    local BACKUP_FILE="$NAS_BACKUP/store-$TS.json"

    if [ ! -d "$NAS_BACKUP" ]; then
        mkdir -p "$NAS_BACKUP"
    fi

    cp "$STORE" "$BACKUP_FILE"
    # Also keep a "latest" copy
    cp "$STORE" "$NAS_BACKUP/store-latest.json"

    # Keep only last 30 backups
    ls -t "$NAS_BACKUP"/store-2*.json 2>/dev/null | tail -n +31 | xargs rm -f 2>/dev/null || true

    local COUNT=$(ls "$NAS_BACKUP"/store-2*.json 2>/dev/null | wc -l | tr -d ' ')
    echo -e "${GREEN}Backed up to $BACKUP_FILE ($COUNT backups on NAS)${NC}"
}

cmd_restore() {
    local FILE="${1:-$NAS_BACKUP/store-latest.json}"
    if [ ! -f "$FILE" ]; then
        echo -e "${RED}Backup not found: $FILE${NC}" >&2
        echo "Available backups:"
        ls -lt "$NAS_BACKUP"/store-*.json 2>/dev/null | head -10
        return 1
    fi
    cp "$FILE" "$STORE"
    chmod 600 "$STORE"
    local COUNT=$($JQ '.credentials | length' "$STORE")
    echo -e "${GREEN}Restored $COUNT credentials from $FILE${NC}"
}

cmd_import_env() {
    # Import from an existing .env file
    local FILE="$1"
    if [ ! -f "$FILE" ]; then
        echo -e "${RED}File not found: $FILE${NC}" >&2
        return 1
    fi
    local ADDED=0
    while IFS='=' read -r key value; do
        # Skip comments and empty lines
        [[ "$key" =~ ^#.*$ ]] && continue
        [[ -z "$key" ]] && continue
        # Remove quotes from value
        value=$(echo "$value" | sed 's/^["'\''"]//;s/["'\''"]$//')
        cmd_add "$key" "$value" "imported from $FILE" 2>/dev/null
        ADDED=$((ADDED + 1))
    done < "$FILE"
    echo -e "${GREEN}Imported $ADDED credentials from $FILE${NC}"
}

usage() {
    cat << 'EOF'
cred-manager.sh - Credential management for OpenClaw bots

Usage:
  cred-manager.sh add <NAME> [VALUE] [DESCRIPTION]
  cred-manager.sh list
  cred-manager.sh get <NAME>
  cred-manager.sh delete <NAME>
  cred-manager.sh export          Generate env.secrets for docker-compose
  cred-manager.sh backup          Backup to NAS
  cred-manager.sh restore [FILE]  Restore from NAS (default: latest)
  cred-manager.sh import <FILE>   Import from .env file

Paths:
  Store:    /Users/fangjin/.credentials/store.json
  Export:   /Users/fangjin/.credentials/env.secrets
  Backups:  /Users/fangjin/nas/.credentials/
EOF
}

# ---- Main ----
init

case "${1:-help}" in
    add)     cmd_add "${2:-}" "${3:-}" "${4:-}" ;;
    list|ls) cmd_list ;;
    get)     cmd_get "${2:?'name required'}" ;;
    delete|rm) cmd_delete "${2:?'name required'}" ;;
    export)  cmd_export ;;
    backup)  cmd_backup ;;
    restore) cmd_restore "${2:-}" ;;
    import)  cmd_import_env "${2:?'file required'}" ;;
    *)       usage ;;
esac
