#!/usr/bin/env python3
"""Hook v7: fix duplicate notifications + empty Result in Telegram.

Root cause analysis:
1. Hook fires on Stop/SessionEnd for ALL Claude Code sessions on Mac Mini
2. Non-task sessions (manual usage) fall back to ${RESULT_DIR}/task-meta.json
3. This re-triggers notifications for the last dispatched task
4. Telegram notification used $OUTPUT (verbose stderr = empty) instead of $CLEAN_RESULT

Fixes:
- After processing, rename task-meta.json -> task-meta.json.done (prevents re-processing)
- Only use results dir fallback if task-meta.json hasn't been processed yet
- Use CLEAN_RESULT for Telegram notification summary (not just verbose OUTPUT)
- Add RESULT_SUMMARY from CLEAN_RESULT for inject text too
"""
import paramiko
import sys

sys.stdout.reconfigure(encoding='utf-8', errors='replace')

c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect("192.168.21.111", username="fangjin", password="YYZZ54321!")

# ============================================================
# Hook v7
# ============================================================
_TC = "\u4efb\u52a1\u5b8c\u6210"
_TK = "\u4efb\u52a1"
_OK = "\u5df2\u5b8c\u6210"
_RN = "\u7ed3\u679c\u5df2\u901a\u8fc7 Telegram \u901a\u77e5\u7528\u6237"
_WD = "\u5de5\u4f5c\u76ee\u5f55"
_TS = "\u4efb\u52a1\u72b6\u6001"
_SM = "\u8f93\u51fa\u6458\u8981"

INJECT_LINE = (
    '    INJECT_TEXT="[{tc}] {tk} \'${{TASK_NAME}}\' {ok}\u3002{rn}\u3002\n'
    '{wd}: ${{CWD}}\n'
    '{ts}: {ok} (exit_code=0)\n'
    '{sm}: ${{RESULT_SUMMARY}}"'
).format(tc=_TC, tk=_TK, ok=_OK, rn=_RN, wd=_WD, ts=_TS, sm=_SM)

lines = []
def L(s=""): lines.append(s)

L("#!/bin/bash")
L("# Claude Code Stop Hook v7: fix duplicate notifications + empty Result")
L("")
L("set -uo pipefail")
L("")
L('RESULT_DIR="/Users/fangjin/claude-code-results"')
L('LOG="${RESULT_DIR}/hook.log"')
L("JQ=/usr/bin/jq")
L('TG_BOT_TOKEN="8586496186:AAF5ZlW1811IbPKwvMr2FzeTmI7VIjDwTls"')
L('TG_PROXY_IP="138.68.44.141"')
L('TG_API="https://api.telegram.org/bot${TG_BOT_TOKEN}"')
L("")
L("# Relay bot (sends clean Claude Code output to Claude_test group)")
L('RELAY_BOT_TOKEN="7589272367:AAGYC28tn02qps-usiTiBnI0E-PktyxSrVs"')
L('RELAY_CHAT_ID="-1003849405283"')
L('RELAY_API="https://api.telegram.org/bot${RELAY_BOT_TOKEN}"')
L("")
L('mkdir -p "$RESULT_DIR"')
L('log() { echo "[$(date -u +"%Y-%m-%dT%H:%M:%SZ")] $*" >> "$LOG"; }')
L("")
L('log "=== Hook v7 fired ==="')
L("")
L('INPUT=""')
L("if [ -t 0 ]; then")
L('    log "stdin is tty, skip"')
L("elif [ -e /dev/stdin ]; then")
L('    INPUT=$(timeout 2 cat /dev/stdin 2>/dev/null || cat /dev/stdin 2>/dev/null || true)')
L("fi")
L("")
L('SESSION_ID=$(echo "$INPUT" | $JQ -r \'.session_id // "unknown"\' 2>/dev/null || echo "unknown")')
L('CWD=$(echo "$INPUT" | $JQ -r \'.cwd // ""\' 2>/dev/null || echo "")')
L('EVENT=$(echo "$INPUT" | $JQ -r \'.hook_event_name // "unknown"\' 2>/dev/null || echo "unknown")')
L('log "session=$SESSION_ID cwd=$CWD event=$EVENT"')
L("")
L("# Per-session 30s dedup lock")
L('SAFE_SID=$(echo "$SESSION_ID" | tr -cd "a-zA-Z0-9_-" | head -c 60)')
L('LOCK_FILE="${RESULT_DIR}/.hook-lock-${SAFE_SID}"')
L('if [ -f "$LOCK_FILE" ]; then')
L('    LOCK_TIME=$(stat -f %m "$LOCK_FILE" 2>/dev/null || echo 0)')
L("    NOW=$(date +%s)")
L("    AGE=$(( NOW - LOCK_TIME ))")
L('    if [ "$AGE" -lt 30 ]; then')
L('        log "Duplicate hook for session $SAFE_SID within ${AGE}s, skipping"')
L("        exit 0")
L("    fi")
L("fi")
L('touch "$LOCK_FILE"')
L('find "$RESULT_DIR" -name ".hook-lock-*" -mmin +5 -delete 2>/dev/null || true')
L("")
L("sleep 2")
L("")
L("# ===== v7 FIX: Determine if this is a dispatched task session =====")
L("# A dispatched task has task-meta.json in its cwd (written by runner)")
L("# Non-task sessions (manual Claude Code) should NOT trigger notifications")
L('IS_TASK_SESSION=false')
L('if [ -n "$CWD" ] && [ -f "$CWD/task-meta.json" ]; then')
L('    IS_TASK_SESSION=true')
L('    log "Task session detected (task-meta.json in cwd)"')
L('elif [ -f "${RESULT_DIR}/task-meta.json" ]; then')
L('    # Fallback: check if this task was already processed')
L('    FALLBACK_TASK=$($JQ -r \'.name // "unknown"\' "${RESULT_DIR}/task-meta.json" 2>/dev/null || echo "unknown")')
L('    SAFE_FT=$(echo "$FALLBACK_TASK" | tr -cd "a-zA-Z0-9_-" | head -c 60)')
L('    if [ -f "${RESULT_DIR}/.processed-${SAFE_FT}" ]; then')
L('        log "Task $FALLBACK_TASK already processed, skipping non-task session"')
L('        exit 0')
L("    fi")
L('    # Not processed yet - this might be the first hook firing for this task')
L('    # Only allow if the task started recently (within 10 minutes)')
L('    TASK_START=$($JQ -r \'.started_at // ""\' "${RESULT_DIR}/task-meta.json" 2>/dev/null || echo "")')
L('    if [ -n "$TASK_START" ]; then')
L('        TASK_TS=$(date -j -f "%Y-%m-%dT%H:%M:%SZ" "$TASK_START" +%s 2>/dev/null || echo 0)')
L("        NOW=$(date +%s)")
L("        TASK_AGE=$(( NOW - TASK_TS ))")
L('        if [ "$TASK_AGE" -gt 600 ]; then')
L('            log "Stale task-meta.json ($FALLBACK_TASK, ${TASK_AGE}s old), skipping"')
L("            exit 0")
L("        fi")
L("    fi")
L('    IS_TASK_SESSION=true')
L('    log "Using fallback task-meta.json for $FALLBACK_TASK"')
L("else")
L('    log "No task-meta.json found anywhere, skipping (not a task session)"')
L("    exit 0")
L("fi")
L("")
L("# Read verbose output (for summary/inject)")
L('OUTPUT=""')
L('if [ -n "$CWD" ] && [ -f "$CWD/task-output.txt" ] && [ -s "$CWD/task-output.txt" ]; then')
L('    OUTPUT=$(tail -c 4000 "$CWD/task-output.txt")')
L('elif [ -f "${RESULT_DIR}/task-output.txt" ] && [ -s "${RESULT_DIR}/task-output.txt" ]; then')
L('    OUTPUT=$(tail -c 4000 "${RESULT_DIR}/task-output.txt")')
L("fi")
L("")
L("# Read CLEAN result (stdout captured by runner v3)")
L('CLEAN_RESULT=""')
L('if [ -n "$CWD" ] && [ -f "$CWD/claude-result.txt" ] && [ -s "$CWD/claude-result.txt" ]; then')
L('    CLEAN_RESULT=$(cat "$CWD/claude-result.txt")')
L('    log "Clean result: ${#CLEAN_RESULT} chars from $CWD/claude-result.txt"')
L('elif [ -f "${RESULT_DIR}/claude-result.txt" ] && [ -s "${RESULT_DIR}/claude-result.txt" ]; then')
L('    CLEAN_RESULT=$(cat "${RESULT_DIR}/claude-result.txt")')
L('    log "Clean result: ${#CLEAN_RESULT} chars from results dir"')
L("else")
L('    log "No claude-result.txt found"')
L("fi")
L("")
L("# Read task metadata")
L('TASK_NAME="unknown"')
L('TELEGRAM_GROUP=""')
L('GATEWAY_PORT="18789"')
L('META_FILE=""')
L('if [ -n "$CWD" ] && [ -f "$CWD/task-meta.json" ]; then')
L('    META_FILE="$CWD/task-meta.json"')
L('elif [ -f "${RESULT_DIR}/task-meta.json" ]; then')
L('    META_FILE="${RESULT_DIR}/task-meta.json"')
L("fi")
L('if [ -n "$META_FILE" ]; then')
L('    TASK_NAME=$($JQ -r \'.name // .task_name // "unknown"\' "$META_FILE" 2>/dev/null || echo "unknown")')
L('    TELEGRAM_GROUP=$($JQ -r \'.telegram_group // ""\' "$META_FILE" 2>/dev/null || echo "")')
L('    GATEWAY_PORT=$($JQ -r \'.gateway_port // "18789"\' "$META_FILE" 2>/dev/null || echo "18789")')
L('    log "Meta: task=$TASK_NAME group=$TELEGRAM_GROUP port=$GATEWAY_PORT"')
L("fi")
L("")
L("# Write latest.json")
L("$JQ -n \\")
L('    --arg sid "$SESSION_ID" --arg ts "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \\')
L('    --arg cwd "$CWD" --arg event "$EVENT" --arg output "$OUTPUT" \\')
L('    --arg task "$TASK_NAME" --arg group "$TELEGRAM_GROUP" \\')
L("""    '{session_id: $sid, timestamp: $ts, cwd: $cwd, event: $event, output: $output, task_name: $task, telegram_group: $group, status: "done"}' \\""")
L('    > "${RESULT_DIR}/latest.json" 2>/dev/null')
L("")
L("# Per-task result file")
L('SAFE_TASK=$(echo "$TASK_NAME" | tr -cd "a-zA-Z0-9_-" | head -c 60)')
L('if [ -n "$SAFE_TASK" ] && [ "$SAFE_TASK" != "unknown" ]; then')
L("    $JQ -n \\")
L('        --arg sid "$SESSION_ID" --arg ts "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \\')
L('        --arg cwd "$CWD" --arg event "$EVENT" --arg output "$OUTPUT" \\')
L('        --arg task "$TASK_NAME" --arg group "$TELEGRAM_GROUP" --arg port "$GATEWAY_PORT" \\')
L("""        '{session_id: $sid, timestamp: $ts, cwd: $cwd, event: $event, output: $output, task_name: $task, telegram_group: $group, gateway_port: $port, status: "done"}' \\""")
L('        > "${RESULT_DIR}/result-${SAFE_TASK}.json" 2>/dev/null')
L("fi")
L("")
L("# ===== v7 FIX: Telegram notification uses CLEAN_RESULT instead of verbose OUTPUT =====")
L('if [ -n "$TELEGRAM_GROUP" ]; then')
L("    # Prefer clean result, fall back to verbose output")
L('    if [ -n "$CLEAN_RESULT" ]; then')
L("        SUMMARY=$(echo \"$CLEAN_RESULT\" | tail -c 600 | tr '\\n' ' ')")
L("    else")
L("        SUMMARY=$(echo \"$OUTPUT\" | tail -c 600 | tr '\\n' ' ')")
L("    fi")
L('    MSG="Claude Code task done')
L('Task: ${TASK_NAME}')
L('Result:')
L('${SUMMARY:0:500}"')
L("    curl -s \\")
L('        --resolve "api.telegram.org:443:${TG_PROXY_IP}" \\')
L('        "${TG_API}/sendMessage" \\')
L('        --data-urlencode "chat_id=${TELEGRAM_GROUP}" \\')
L('        --data-urlencode "text=${MSG}" \\')
L("        --max-time 10 > /dev/null 2>&1 \\")
L('        && log "Telegram sent to $TELEGRAM_GROUP" \\')
L('        || log "Telegram send failed"')
L("fi")
L("")
L("# ===== Relay CLEAN result to Claude_test group =====")
L('RELAY_CONTENT=""')
L('if [ -n "$CLEAN_RESULT" ]; then')
L('    RELAY_CONTENT="$CLEAN_RESULT"')
L('    log "Relay: using clean result"')
L('elif [ -n "$OUTPUT" ]; then')
L('    RELAY_CONTENT="$OUTPUT"')
L('    log "Relay: fallback to verbose output"')
L("fi")
L("")
L('if [ -n "$RELAY_CONTENT" ]; then')
L('    CONTENT_LEN=${#RELAY_CONTENT}')
L('    log "Relay: content=$CONTENT_LEN chars"')
L('    if [ "$CONTENT_LEN" -gt 4000 ]; then')
L('        RELAY_FILE="${RESULT_DIR}/relay-${SAFE_TASK:-output}.txt"')
L('        echo "$RELAY_CONTENT" > "$RELAY_FILE"')
L('        CAPTION="[${TASK_NAME}] Claude Code result (${CONTENT_LEN} chars)"')
L("        curl -s \\")
L('            --resolve "api.telegram.org:443:${TG_PROXY_IP}" \\')
L('            "${RELAY_API}/sendDocument" \\')
L('            -F "chat_id=${RELAY_CHAT_ID}" \\')
L('            -F "caption=${CAPTION}" \\')
L('            -F "document=@${RELAY_FILE};filename=${TASK_NAME}-result.txt" \\')
L("            --max-time 30 > /dev/null 2>&1 \\")
L('            && log "Relay: sent document to Claude_test" \\')
L('            || log "Relay: document send failed"')
L('        rm -f "$RELAY_FILE"')
L("    else")
L('        RELAY_MSG="[${TASK_NAME}]')
L('${RELAY_CONTENT}"')
L("        curl -s \\")
L('            --resolve "api.telegram.org:443:${TG_PROXY_IP}" \\')
L('            "${RELAY_API}/sendMessage" \\')
L('            --data-urlencode "chat_id=${RELAY_CHAT_ID}" \\')
L('            --data-urlencode "text=${RELAY_MSG}" \\')
L("            --max-time 10 > /dev/null 2>&1 \\")
L('            && log "Relay: sent to Claude_test" \\')
L('            || log "Relay: send failed"')
L("    fi")
L("else")
L('    log "Relay: no content"')
L("fi")
L("")
L("# ===== v7 FIX: Mark task as processed to prevent duplicate notifications =====")
L('if [ -n "$SAFE_TASK" ] && [ "$SAFE_TASK" != "unknown" ]; then')
L('    touch "${RESULT_DIR}/.processed-${SAFE_TASK}"')
L('    # Rename task-meta.json in results dir to prevent fallback re-processing')
L('    if [ -f "${RESULT_DIR}/task-meta.json" ]; then')
L('        mv "${RESULT_DIR}/task-meta.json" "${RESULT_DIR}/task-meta.json.done" 2>/dev/null || true')
L('        log "Marked task $SAFE_TASK as processed"')
L("    fi")
L('    # Clean old processed markers (>1 hour)')
L('    find "$RESULT_DIR" -name ".processed-*" -mmin +60 -delete 2>/dev/null || true')
L("fi")
L("")
L("# Inject results into bot session history")
L('if [ -n "$TELEGRAM_GROUP" ]; then')
L('    case "$TELEGRAM_GROUP" in')
L('        -*)  SESSION_KEY="agent:main:telegram:group:${TELEGRAM_GROUP}" ;;')
L('        *)   SESSION_KEY="agent:main:telegram:dm:${TELEGRAM_GROUP}" ;;')
L("    esac")
L("    # v7: use CLEAN_RESULT for inject summary too")
L('    if [ -n "$CLEAN_RESULT" ]; then')
L("        RESULT_SUMMARY=$(echo \"$CLEAN_RESULT\" | head -c 800 | tr '\\n' ' ')")
L("    else")
L("        RESULT_SUMMARY=$(echo \"$OUTPUT\" | head -c 800 | tr '\\n' ' ')")
L("    fi")
lines.append(INJECT_LINE)
L("")
L("    (")
L('        /opt/homebrew/bin/node /Users/fangjin/claude-code-inject.js "$INJECT_TEXT" "$SESSION_KEY" 15000 3 "$GATEWAY_PORT" \\')
L('            >> "$LOG" 2>&1 \\')
L('            && log "Chat.inject sent to $SESSION_KEY (port=$GATEWAY_PORT)" \\')
L('            || log "Chat.inject failed (non-fatal)"')
L("    ) &")
L('    log "Chat.inject scheduled (15s delay, port=$GATEWAY_PORT)"')
L("else")
L('    log "No telegram_group, skipping"')
L("fi")
L("")
L('log "=== Hook v7 completed ==="')
L("exit 0")

HOOK_CONTENT = "\n".join(lines) + "\n"

# ============================================================
# Deploy
# ============================================================
print("Deploying hook v7...")

# Backup v6
print("\n1. Backing up hook v6...")
si, so, se = c.exec_command("cp /Users/fangjin/.claude/hooks/notify-openclaw.sh /Users/fangjin/.claude/hooks/notify-openclaw.sh.bak-v6")
so.read()

# Deploy hook v7
print("2. Writing hook v7...")
sftp = c.open_sftp()
with sftp.open("/Users/fangjin/.claude/hooks/notify-openclaw.sh", "wb") as f:
    f.write(HOOK_CONTENT.encode("utf-8"))
sftp.close()
si, so, se = c.exec_command("chmod +x /Users/fangjin/.claude/hooks/notify-openclaw.sh")
so.read()

# Verify
si, so, se = c.exec_command("grep -c 'v7' /Users/fangjin/.claude/hooks/notify-openclaw.sh")
ver = so.read().decode().strip()
print(f"   Hook version: {'v7 OK' if int(ver) >= 1 else 'WARNING'}")

si, so, se = c.exec_command("wc -l /Users/fangjin/.claude/hooks/notify-openclaw.sh")
print(f"   Lines: {so.read().decode().strip()}")

si, so, se = c.exec_command("grep 'processed\\|IS_TASK_SESSION\\|CLEAN_RESULT.*SUMMARY' /Users/fangjin/.claude/hooks/notify-openclaw.sh | head -5")
print(f"   v7 markers: {so.read().decode().strip()}")

# Clean up stale state from the ghost task
print("\n3. Cleaning stale state...")
si, so, se = c.exec_command("rm -f /Users/fangjin/claude-code-results/task-meta.json /Users/fangjin/claude-code-results/.hook-lock-*")
so.read()
print("   Removed stale task-meta.json and lock files")

c.close()
print("\nDone! Hook v7 deployed.")
print("Fixes:")
print("- Non-task sessions no longer trigger notifications")
print("- Processed tasks marked to prevent duplicate notifications")
print("- Telegram notification now shows clean result (not empty verbose output)")
print("- Stale task-meta.json (>10min) ignored")
