#!/usr/bin/env python3
"""Deploy hook v3 to Mac Mini - include results directly in chat.send message"""
import paramiko

# Chinese text (unicode escapes survive Write tool encoding issues)
_TC = "\u4efb\u52a1\u5b8c\u6210"                 # 任务完成
_TK = "\u4efb\u52a1"                             # 任务
_OK = "\u5df2\u5b8c\u6210"                       # 已完成
_RN = "\u7ed3\u679c\u5df2\u901a\u8fc7 Telegram \u901a\u77e5\u7528\u6237"  # 结果已通过 Telegram 通知用户
_WD = "\u5de5\u4f5c\u76ee\u5f55"                 # 工作目录
_TS = "\u4efb\u52a1\u72b6\u6001"                 # 任务状态
_SM = "\u8f93\u51fa\u6458\u8981"                 # 输出摘要

# INJECT_TEXT: assistant message for session history context
# Written as what the bot "said" (chat.inject adds assistant messages)
INJECT_LINE = (
    '    INJECT_TEXT="[{tc}] {tk} \'${{TASK_NAME}}\' {ok}\u3002{rn}\u3002\n'
    '{wd}: ${{CWD}}\n'
    '{ts}: {ok} (exit_code=0)\n'
    '{sm}: ${{RESULT_SUMMARY}}"'
).format(tc=_TC, tk=_TK, ok=_OK, rn=_RN, wd=_WD, ts=_TS, sm=_SM)

# Build hook script as list of lines (avoids all escaping confusion)
lines = []
def L(s=""): lines.append(s)

L("#!/bin/bash")
L("# Claude Code Stop Hook v3: notify AGI + send Telegram message")
L("# Key change: include results directly in chat.send message")
L("")
L("set -uo pipefail")
L("")
L('RESULT_DIR="/Users/fangjin/claude-code-results"')
L('LOG="${RESULT_DIR}/hook.log"')
L("JQ=/usr/bin/jq")
L("")
L('# Telegram Bot API (via VPS proxy to bypass GFW)')
L('TG_BOT_TOKEN="8586496186:AAF5ZlW1811IbPKwvMr2FzeTmI7VIjDwTls"')
L('TG_PROXY_IP="138.68.44.141"')
L('TG_API="https://api.telegram.org/bot${TG_BOT_TOKEN}"')
L("")
L('mkdir -p "$RESULT_DIR"')
L("")
L('log() { echo "[$(date -u +"%Y-%m-%dT%H:%M:%SZ")] $*" >> "$LOG"; }')
L("")
L('log "=== Hook fired ==="')
L("")
L("# ---- Read stdin ----")
L('INPUT=""')
L("if [ -t 0 ]; then")
L('    log "stdin is tty, skip"')
L("elif [ -e /dev/stdin ]; then")
L('    INPUT=$(timeout 2 cat /dev/stdin 2>/dev/null || cat /dev/stdin 2>/dev/null || true)')
L("fi")
L("")
L('SESSION_ID=$(echo "$INPUT" | $JQ -r \'.session_id // "unknown"\' 2>/dev/null || echo "unknown")')
L('CWD=$(echo "$INPUT" | $JQ -r \'.cwd // ""\' 2>/dev/null || echo "")')
L('EVENT=$(echo "$INPUT" | $JQ -r \'.hook_event_name // "unknown"\' 2>/dev/null || echo "unknown")')
L("")
L('log "session=$SESSION_ID cwd=$CWD event=$EVENT"')
L("")
L("# ---- Deduplication: 30s lock ----")
L('LOCK_FILE="${RESULT_DIR}/.hook-lock"')
L('if [ -f "$LOCK_FILE" ]; then')
L('    LOCK_TIME=$(stat -f %m "$LOCK_FILE" 2>/dev/null || echo 0)')
L("    NOW=$(date +%s)")
L("    AGE=$(( NOW - LOCK_TIME ))")
L('    if [ "$AGE" -lt 30 ]; then')
L('        log "Duplicate hook within ${AGE}s, skipping"')
L("        exit 0")
L("    fi")
L("fi")
L('touch "$LOCK_FILE"')
L("")
L("# ---- Wait for tee pipe to flush ----")
L("sleep 2")
L("")
L("# ---- Read output (multiple sources) ----")
L('OUTPUT=""')
L("")
L("# Source 1: task-output.txt in CWD")
L('if [ -n "$CWD" ] && [ -f "$CWD/task-output.txt" ] && [ -s "$CWD/task-output.txt" ]; then')
L('    OUTPUT=$(tail -c 4000 "$CWD/task-output.txt")')
L('    log "Output from $CWD/task-output.txt (${#OUTPUT} chars)"')
L("fi")
L("")
L("# Source 2: result dir fallback")
L('if [ -z "$OUTPUT" ] && [ -f "${RESULT_DIR}/task-output.txt" ] && [ -s "${RESULT_DIR}/task-output.txt" ]; then')
L('    OUTPUT=$(tail -c 4000 "${RESULT_DIR}/task-output.txt")')
L('    log "Output from result dir (${#OUTPUT} chars)"')
L("fi")
L("")
L("# Source 3: directory listing")
L('if [ -z "$OUTPUT" ] && [ -n "$CWD" ] && [ -d "$CWD" ]; then')
L("    FILES=$(ls -1t \"$CWD\" 2>/dev/null | head -20 | tr '\\n' ', ')")
L('    OUTPUT="Working dir: ${CWD}  Files: ${FILES}"')
L('    log "Output from dir listing"')
L("fi")
L("")
L("# ---- Read task metadata ----")
L('TASK_NAME="unknown"')
L('TELEGRAM_GROUP=""')
L("")
L('META_FILE=""')
L('if [ -n "$CWD" ] && [ -f "$CWD/task-meta.json" ]; then')
L('    META_FILE="$CWD/task-meta.json"')
L('elif [ -f "${RESULT_DIR}/task-meta.json" ]; then')
L('    META_FILE="${RESULT_DIR}/task-meta.json"')
L("fi")
L("")
L('if [ -n "$META_FILE" ]; then')
L('    TASK_NAME=$($JQ -r \'.name // .task_name // "unknown"\' "$META_FILE" 2>/dev/null || echo "unknown")')
L('    TELEGRAM_GROUP=$($JQ -r \'.telegram_group // ""\' "$META_FILE" 2>/dev/null || echo "")')
L('    log "Meta: task=$TASK_NAME group=$TELEGRAM_GROUP"')
L("fi")
L("")
L("# ---- Read created/modified files ----")
L('CREATED_FILES=""')
L('if [ -n "$CWD" ] && [ -d "$CWD" ]; then')
L("    CREATED_FILES=$(find \"$CWD\" -maxdepth 2 -newer \"$LOCK_FILE\" -type f 2>/dev/null | head -10 | tr '\\n' ', ')")
L("fi")
L("")
L("# ---- Write latest.json ----")
L("$JQ -n \\")
L('    --arg sid "$SESSION_ID" \\')
L('    --arg ts "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \\')
L('    --arg cwd "$CWD" \\')
L('    --arg event "$EVENT" \\')
L('    --arg output "$OUTPUT" \\')
L('    --arg task "$TASK_NAME" \\')
L('    --arg group "$TELEGRAM_GROUP" \\')
L("    '{session_id: $sid, timestamp: $ts, cwd: $cwd, event: $event, output: $output, task_name: $task, telegram_group: $group, status: \"done\"}' \\")
L('    > "${RESULT_DIR}/latest.json" 2>/dev/null')
L("")
L('log "Wrote latest.json"')
L("")
L("# ---- Send Telegram message via Bot API ----")
L('if [ -n "$TELEGRAM_GROUP" ]; then')
L("    SUMMARY=$(echo \"$OUTPUT\" | tail -c 600 | tr '\\n' ' ')")
L('    MSG="Claude Code task done')
L('Task: ${TASK_NAME}')
L('Result:')
L('${SUMMARY:0:500}"')
L("")
L("    TG_RESULT=$(curl -s \\")
L('        --resolve "api.telegram.org:443:${TG_PROXY_IP}" \\')
L('        "${TG_API}/sendMessage" \\')
L('        --data-urlencode "chat_id=${TELEGRAM_GROUP}" \\')
L('        --data-urlencode "text=${MSG}" \\')
L("        --max-time 10 2>&1)")
L("")
L("    if echo \"$TG_RESULT\" | $JQ -e '.ok' > /dev/null 2>&1; then")
L('        log "Telegram message sent to $TELEGRAM_GROUP"')
L("    else")
L('        log "Telegram send failed: $TG_RESULT"')
L("    fi")
L("fi")
L("")
L("# ---- Write pending-wake.json (heartbeat fallback) ----")
L("$JQ -n \\")
L('    --arg task "$TASK_NAME" \\')
L('    --arg group "$TELEGRAM_GROUP" \\')
L('    --arg ts "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \\')
L("    --arg summary \"$(echo \"$OUTPUT\" | head -c 500 | tr '\\n' ' ')\" \\")
L("    '{task_name: $task, telegram_group: $group, timestamp: $ts, summary: $summary, processed: false}' \\")
L('    > "${RESULT_DIR}/pending-wake.json" 2>/dev/null')
L("")
L('log "Wrote pending-wake.json"')
L("")
L("# ---- Inject results into agent session history (chat.inject, no agent run) ----")
L("# This adds an assistant message so the agent knows the task completed")
L('if [ -n "$TELEGRAM_GROUP" ]; then')
L("    case \"$TELEGRAM_GROUP\" in")
L('        -*)  SESSION_KEY="agent:main:telegram:group:${TELEGRAM_GROUP}" ;;')
L('        *)   SESSION_KEY="agent:main:telegram:dm:${TELEGRAM_GROUP}" ;;')
L("    esac")
L("")
L("    # Build message with results included directly")
L("    RESULT_SUMMARY=$(echo \"$OUTPUT\" | head -c 800 | tr '\\n' ' ')")
# Insert the INJECT_TEXT line (with Chinese characters)
lines.append(INJECT_LINE)
L("")
L("    # Background: delay 15s, then send with 3 retries")
L("    (")
L('        /opt/homebrew/bin/node /Users/fangjin/claude-code-inject.js "$INJECT_TEXT" "$SESSION_KEY" 15000 3 \\')
L('            >> "$LOG" 2>&1 \\')
L('            && log "Chat.inject sent to $SESSION_KEY" \\')
L('            || log "Chat.inject failed after retries (non-fatal)"')
L("    ) &")
L('    log "Chat.inject scheduled in background (15s delay, 3 retries)"')
L("else")
L('    log "No telegram_group, skipping chat.send"')
L("fi")
L("")
L('log "=== Hook completed ==="')
L("exit 0")

# Join all lines into the final hook script
HOOK_CONTENT = "\n".join(lines) + "\n"

# Deploy to Mac Mini
HOOK_PATH = "/Users/fangjin/.claude/hooks/notify-openclaw.sh"

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect("192.168.21.111", username="fangjin", password="YYZZ54321!")

sftp = client.open_sftp()
with sftp.open(HOOK_PATH, "wb") as f:
    f.write(HOOK_CONTENT.encode("utf-8"))
sftp.close()

stdin, stdout, stderr = client.exec_command(f"chmod +x {HOOK_PATH}")
stdout.read()

# Verify deployment
sftp = client.open_sftp()
with sftp.open(HOOK_PATH, "rb") as f:
    content = f.read().decode("utf-8")
sftp.close()

line_count = content.count("\n")
has_inject = "INJECT_TEXT=" in content
has_chat_send = "chat.send" in content.lower() or "inject.js" in content

# Check for Chinese characters in INJECT_TEXT line
for line in content.split("\n"):
    if "INJECT_TEXT=" in line:
        has_chinese = any(ord(c) > 0x4e00 for c in line)
        print(f"INJECT_TEXT line ({len(line)} chars, chinese={has_chinese}):")
        print(f"  {line.strip()[:150]}...")
        break

print(f"\nDeployed hook v3: {line_count} lines, inject={has_inject}, chat_send={has_chat_send}")

client.close()
print("Done!")
