#!/usr/bin/env python3
"""Fix hook deduplication for concurrent multi-bot Claude Code usage.
Changes:
1. Lock file: global → per-session (SESSION_ID based)
2. pending-wake.json: shared → per-task
3. Add cleanup of stale lock files (>5min)
"""
import paramiko

c = paramiko.SSHClient()
c.set_missing_host_key_policy(paramiko.AutoAddPolicy())
c.connect("192.168.21.111", username="fangjin", password="YYZZ54321!")

# Chinese strings (written as literals to avoid encoding issues)
_TC = "\u4efb\u52a1\u5b8c\u6210"
_TK = "\u4efb\u52a1"
_OK = "\u5df2\u5b8c\u6210"
_RN = "\u7ed3\u679c\u5df2\u901a\u8fc7 Telegram \u901a\u77e5\u7528\u6237"
_WD = "\u5de5\u4f5c\u76ee\u5f55"
_TS = "\u4efb\u52a1\u72b6\u6001"
_SM = "\u8f93\u51fa\u6458\u8981"

INJECT_LINE = (
    '    INJECT_TEXT="[{tc}] {tk} \'${{TASK_NAME}}\' {ok}\u3002{rn}\u3002\n'
    '{wd}: ${{CWD}}\n'
    '{ts}: {ok} (exit_code=0)\n'
    '{sm}: ${{RESULT_SUMMARY}}"'
).format(tc=_TC, tk=_TK, ok=_OK, rn=_RN, wd=_WD, ts=_TS, sm=_SM)

lines = []
def L(s=""): lines.append(s)

L("#!/bin/bash")
L("# Claude Code Stop Hook v5: per-session dedup for concurrent multi-bot usage")
L("")
L("set -uo pipefail")
L("")
L('RESULT_DIR="/Users/fangjin/claude-code-results"')
L('LOG="${RESULT_DIR}/hook.log"')
L("JQ=/usr/bin/jq")
L('TG_BOT_TOKEN="8586496186:AAF5ZlW1811IbPKwvMr2FzeTmI7VIjDwTls"')
L('TG_PROXY_IP="138.68.44.141"')
L('TG_API="https://api.telegram.org/bot${TG_BOT_TOKEN}"')
L("")
L('mkdir -p "$RESULT_DIR"')
L('log() { echo "[$(date -u +"%Y-%m-%dT%H:%M:%SZ")] $*" >> "$LOG"; }')
L("")
L('log "=== Hook fired ==="')
L("")
L('INPUT=""')
L("if [ -t 0 ]; then")
L('    log "stdin is tty, skip"')
L("elif [ -e /dev/stdin ]; then")
L('    INPUT=$(timeout 2 cat /dev/stdin 2>/dev/null || cat /dev/stdin 2>/dev/null || true)')
L("fi")
L("")
L('SESSION_ID=$(echo "$INPUT" | $JQ -r \'.session_id // "unknown"\' 2>/dev/null || echo "unknown")')
L('CWD=$(echo "$INPUT" | $JQ -r \'.cwd // ""\' 2>/dev/null || echo "")')
L('EVENT=$(echo "$INPUT" | $JQ -r \'.hook_event_name // "unknown"\' 2>/dev/null || echo "unknown")')
L('log "session=$SESSION_ID cwd=$CWD event=$EVENT"')
L("")
L("# Deduplication: per-session 30s lock (allows concurrent tasks from different sessions)")
L('SAFE_SID=$(echo "$SESSION_ID" | tr -cd "a-zA-Z0-9_-" | head -c 60)')
L('LOCK_FILE="${RESULT_DIR}/.hook-lock-${SAFE_SID}"')
L('if [ -f "$LOCK_FILE" ]; then')
L('    LOCK_TIME=$(stat -f %m "$LOCK_FILE" 2>/dev/null || echo 0)')
L("    NOW=$(date +%s)")
L("    AGE=$(( NOW - LOCK_TIME ))")
L('    if [ "$AGE" -lt 30 ]; then')
L('        log "Duplicate hook for session $SAFE_SID within ${AGE}s, skipping"')
L("        exit 0")
L("    fi")
L("fi")
L('touch "$LOCK_FILE"')
L("")
L("# Cleanup stale lock files (>5 min old)")
L('find "$RESULT_DIR" -name ".hook-lock-*" -mmin +5 -delete 2>/dev/null || true')
L("")
L("sleep 2")
L("")
L("# Read output")
L('OUTPUT=""')
L('if [ -n "$CWD" ] && [ -f "$CWD/task-output.txt" ] && [ -s "$CWD/task-output.txt" ]; then')
L('    OUTPUT=$(tail -c 4000 "$CWD/task-output.txt")')
L('elif [ -f "${RESULT_DIR}/task-output.txt" ] && [ -s "${RESULT_DIR}/task-output.txt" ]; then')
L('    OUTPUT=$(tail -c 4000 "${RESULT_DIR}/task-output.txt")')
L('elif [ -n "$CWD" ] && [ -d "$CWD" ]; then')
L("    FILES=$(ls -1t \"$CWD\" 2>/dev/null | head -20 | tr '\\n' ', ')")
L('    OUTPUT="Working dir: ${CWD}  Files: ${FILES}"')
L("fi")
L("")
L("# Read task metadata")
L('TASK_NAME="unknown"')
L('TELEGRAM_GROUP=""')
L('GATEWAY_PORT="18789"')
L('META_FILE=""')
L('if [ -n "$CWD" ] && [ -f "$CWD/task-meta.json" ]; then')
L('    META_FILE="$CWD/task-meta.json"')
L('elif [ -f "${RESULT_DIR}/task-meta.json" ]; then')
L('    META_FILE="${RESULT_DIR}/task-meta.json"')
L("fi")
L('if [ -n "$META_FILE" ]; then')
L('    TASK_NAME=$($JQ -r \'.name // .task_name // "unknown"\' "$META_FILE" 2>/dev/null || echo "unknown")')
L('    TELEGRAM_GROUP=$($JQ -r \'.telegram_group // ""\' "$META_FILE" 2>/dev/null || echo "")')
L('    GATEWAY_PORT=$($JQ -r \'.gateway_port // "18789"\' "$META_FILE" 2>/dev/null || echo "18789")')
L('    log "Meta: task=$TASK_NAME group=$TELEGRAM_GROUP port=$GATEWAY_PORT"')
L("fi")
L("")
L("# Write latest.json (shared, for quick reference)")
L("$JQ -n \\")
L('    --arg sid "$SESSION_ID" --arg ts "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \\')
L('    --arg cwd "$CWD" --arg event "$EVENT" --arg output "$OUTPUT" \\')
L('    --arg task "$TASK_NAME" --arg group "$TELEGRAM_GROUP" \\')
L("    '{session_id: $sid, timestamp: $ts, cwd: $cwd, event: $event, output: $output, task_name: $task, telegram_group: $group, status: \"done\"}' \\")
L('    > "${RESULT_DIR}/latest.json" 2>/dev/null')
L("")
L("# Also write per-task result file (won't be overwritten by other tasks)")
L('SAFE_TASK=$(echo "$TASK_NAME" | tr -cd "a-zA-Z0-9_-" | head -c 60)')
L('if [ -n "$SAFE_TASK" ] && [ "$SAFE_TASK" != "unknown" ]; then')
L("    $JQ -n \\")
L('        --arg sid "$SESSION_ID" --arg ts "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \\')
L('        --arg cwd "$CWD" --arg event "$EVENT" --arg output "$OUTPUT" \\')
L('        --arg task "$TASK_NAME" --arg group "$TELEGRAM_GROUP" --arg port "$GATEWAY_PORT" \\')
L("        '{session_id: $sid, timestamp: $ts, cwd: $cwd, event: $event, output: $output, task_name: $task, telegram_group: $group, gateway_port: $port, status: \"done\"}' \\")
L('        > "${RESULT_DIR}/result-${SAFE_TASK}.json" 2>/dev/null')
L('    log "Wrote result-${SAFE_TASK}.json"')
L("fi")
L("")
L("# Send Telegram message")
L('if [ -n "$TELEGRAM_GROUP" ]; then')
L("    SUMMARY=$(echo \"$OUTPUT\" | tail -c 600 | tr '\\n' ' ')")
L('    MSG="Claude Code task done')
L('Task: ${TASK_NAME}')
L('Result:')
L('${SUMMARY:0:500}"')
L("    curl -s \\")
L('        --resolve "api.telegram.org:443:${TG_PROXY_IP}" \\')
L('        "${TG_API}/sendMessage" \\')
L('        --data-urlencode "chat_id=${TELEGRAM_GROUP}" \\')
L('        --data-urlencode "text=${MSG}" \\')
L("        --max-time 10 > /dev/null 2>&1 \\")
L('        && log "Telegram sent to $TELEGRAM_GROUP" \\')
L('        || log "Telegram send failed"')
L("fi")
L("")
L("# Inject results into bot session history (chat.inject via WebSocket)")
L('if [ -n "$TELEGRAM_GROUP" ]; then')
L("    case \"$TELEGRAM_GROUP\" in")
L('        -*)  SESSION_KEY="agent:main:telegram:group:${TELEGRAM_GROUP}" ;;')
L('        *)   SESSION_KEY="agent:main:telegram:dm:${TELEGRAM_GROUP}" ;;')
L("    esac")
L("    RESULT_SUMMARY=$(echo \"$OUTPUT\" | head -c 800 | tr '\\n' ' ')")
lines.append(INJECT_LINE)
L("")
L("    (")
L('        /opt/homebrew/bin/node /Users/fangjin/claude-code-inject.js "$INJECT_TEXT" "$SESSION_KEY" 15000 3 "$GATEWAY_PORT" \\')
L('            >> "$LOG" 2>&1 \\')
L('            && log "Chat.inject sent to $SESSION_KEY (port=$GATEWAY_PORT)" \\')
L('            || log "Chat.inject failed (non-fatal)"')
L("    ) &")
L('    log "Chat.inject scheduled (15s delay, port=$GATEWAY_PORT)"')
L("else")
L('    log "No telegram_group, skipping"')
L("fi")
L("")
L('log "=== Hook completed ==="')
L("exit 0")

HOOK_CONTENT = "\n".join(lines) + "\n"

# Deploy
print("Deploying hook v5 (per-session dedup)...")
sftp = c.open_sftp()
with sftp.open("/Users/fangjin/.claude/hooks/notify-openclaw.sh", "wb") as f:
    f.write(HOOK_CONTENT.encode("utf-8"))
sftp.close()

si, so, se = c.exec_command("chmod +x /Users/fangjin/.claude/hooks/notify-openclaw.sh")
so.read()

# Verify
si, so, se = c.exec_command("grep -n 'hook-lock' /Users/fangjin/.claude/hooks/notify-openclaw.sh")
out = so.read().decode().strip()
print(f"Lock lines:\n{out}")

si, so, se = c.exec_command("grep -c 'v5' /Users/fangjin/.claude/hooks/notify-openclaw.sh")
ver = so.read().decode().strip()
print(f"Version check: {'v5 found' if ver == '1' else 'WARNING: v5 not found'}")

# Clean up old global lock file
si, so, se = c.exec_command("rm -f /Users/fangjin/claude-code-results/.hook-lock")
so.read()
print("Cleaned up old global lock file")

c.close()
print("\nDone! Hook v5 deployed with per-session deduplication.")
